### ISSUE TITLE
Feature Request: different diagram

### ISSUE THREAD

**Issue by gskyarts** [mittwald/flow#1001]
Hi there,

we have a feature request idea. Currently we are planning a new extension and noticed that we need any diagram components. We think it would be a good addition to be able to build dashboard-like tiles or to visually represent different information in a diagram. The D3js library would be a good lib, but we think classic diagrams would be perfect for now, like bars (horizontal, vertical), cakes / donuts and line diagrams.

Do you thin you could include this feature? We'd really appreciate it!

**Comment by Jan-Eimertenbrink** [comment]
Hey Giovanni,

Supporting a few basic diagram types is already planned in our backlog (see this [issue](https://github.com/mittwald/flow/issues/719)), but it’s not scheduled for the near future. In the meantime, you could try integrating diagrams from other libraries and styling them with our tokens. These are now largely described under [Foundations](https://mittwald.github.io/flow/02-foundations/01-design/02-colors). If you have any questions, feel free to reach out.

**Comment by thueske** [comment]
I would briefly correct the statement: If you are building an extension that is to be integrated into mStudio, an external library is of no use to you, as it would not be rendered. As we will need simple diagrams (see workload indicator) in mStudio in the next 6 months, there will be an implementation within this time.

I am closing this issue as there is already an issue for it.
