### ISSUE TITLE
Render only necessarry parts in code editor for examples

### ISSUE THREAD

**Issue by deder-mw** [mittwald/flow#37]
Render only necessarry parts in code editor for examples and maybe even add a switch to "expand code".

The example tsx file could then look like this:
```tsx
import { Button } from "@mittwald/flow-components/Button";

export default function ButtonSimple() {
  return (
    <>
      <Button>Button</Button>
      <Button variant="primary">Primary</Button>
    </>
  );
}
```

And the code in the live editor would look like this:
```tsx
<Button>Button</Button>
<Button variant="primary">Primary</Button>
```

**Comment by Jan-Eimertenbrink** [comment]
It seems to be already fixed, so I will close the issue. However, we will still remove the semicolons (";") from the code examples within this [issue](https://github.com/mittwald/flow/issues/625).
