### ISSUE TITLE
Button Icon misplaced

### ISSUE THREAD

**Issue by TimAufdemKampe** [mittwald/flow#381]
If the Button has an **custom tabler** Icon and size is set to small the icon is misplaced

Code:
```jsx
<Button size="s" variant="secondary">
    <Icon>
          <IconCircleOff />
    </Icon>
    <Translate i18n="remove" />
</Button>
```

Rendered component:
![Bildschirmfoto 2024-04-24 um 14 07 07](https://github.com/mittwald/flow/assets/22775723/d89ab3d8-345b-420e-a5cf-bba0ad057338)

**Comment by Lisa18289** [comment]
Wenn du den Button mit Icon und Text verwendest musst du den Text in eine Text Komponente packen:

<img width="696" alt="Bildschirmfoto 2024-04-24 um 14 58 00" src="https://github.com/mittwald/flow/assets/84317589/c876b46b-15cd-43c2-8742-1454b71c6c36">

Aber in dem Fall soll das Icon eh weg, aber das hat Jan dir aber schon gesagt ge?
