### ISSUE TITLE
IllustratedMessage has a unused color prop

### ISSUE THREAD

**Issue by maaaathis** [mittwald/flow#390]
The `<IllustratedMessage>` component has a optional `color` prop. The prop is from the type `string | undefined`.
But sadly that prop doesn't change anything. Rather, it is even logically overwritten by the mechanics of the `variant` prop

**Comment by Lisa18289** [comment]
Das color Prop ist halt ein standard HTML Props das wirst du an vielen Stellen finden. Wir werden uns das aber nochmal anschauen wenn wir die Property Tabellen bauen

**Comment by Lisa18289** [comment]
mittlerweile nutzen wir die Prop tatsächlich, daher schließe ich das Issue
