### ISSUE TITLE
Active Tab has wrong border radius at the top

### ISSUE THREAD

**Issue by TimAufdemKampe** [mittwald/flow#404]
![Bildschirmfoto 2024-05-02 um 06 55 51](https://github.com/mittwald/flow/assets/22775723/feac67d6-9c08-442f-bea0-5370e0d3b6da)

**Comment by Lisa18289** [comment]
ah da hat ich Dienstag schon mir Jan geredet, wir schmeißen den Radius raus, habs in diesem MR gleich mit gemacht: https://github.com/mittwald/flow/pull/402
