### ISSUE TITLE
Multiple StatusBadge's in a Header

### ISSUE THREAD

**Issue by maaaathis** [mittwald/flow#433]
Multiple `StatusBadge` components in a `Header` component have a `justify-between` spacing.
I would have expected that, if there were several, they would be arranged together on the right.

![Google Chrome 2024-05-07 10 20 28](https://github.com/mittwald/flow/assets/37186532/9a14858a-f49e-433f-a651-b6f73aaee85c)

**Comment by Lisa18289** [comment]
Wir wollen garnicht mehrere Badges unterstützen, es soll immer nur einen geben. Wenn es mehrere Stati gibt, sollte der wichtigere angezeigt werden
