### ISSUE TITLE
Flow DatePicker closes FlowNext Modal

### ISSUE THREAD

**Issue by maaaathis** [mittwald/flow#445]
https://github.com/mittwald/flow/assets/37186532/a38b1ba3-3baa-4e5b-9e50-c5460277a981

**Comment by mfal** [comment]
Thanks for you bug-report. I think the Modal closes, because it considers the click as "clicked outside". Can you confirm this by setting the `isDismissable` prop to `false` on the Modal.

**Comment by maaaathis** [comment]
> Thanks for you bug report. I think the Modal closes, because it considers the click as "clicked outside". Can you confirm this by setting the `isDismissable` prop to `false` on the Modal.

That makes sense, but the `Modal` component sadly doesn't export an `isDismissable` prop.

**Comment by mfal** [comment]
😅 by now the prop is available. Can you please check it?
