### ISSUE TITLE
Select Component schließt Modal

### ISSUE THREAD

**Issue by Lisa18289** [mittwald/flow#487]
Wird in einem Modal die Select Component verwendet, schließt sich das Modal nach dem öffnen direkt wieder.
zb:
```
 <Modal controller={modalController}>
    <Heading>Wordpress installieren</Heading>
    <Content>
        <Select>
          <Label>Version</Label>
          <Option>6.5.3</Option>
          <Option>6.5.2</Option>
        </Select>
    </Content>
</Modal>
```

Meine Vermutung ist, dass die beiden Overlay Controller nicht miteinander klar kommen, und das Modal auf den falschen hört.

Das gleiche tritt auch auf wenn man ein Context Menu im Modal verwendet.

**Comment by mfal** [comment]
Closed by https://github.com/mittwald/flow/pull/506
