### ISSUE TITLE
ContextMenu tip has a small gap

### ISSUE THREAD

**Issue by TimAufdemKampe** [mittwald/flow#544]
![Bildschirmfoto 2024-06-25 um 09 25 01](https://github.com/mittwald/flow/assets/22775723/b4798f53-b348-4557-9f1a-b85ae8022fc3)

**Comment by Lisa18289** [comment]
Der Tip ist garnicht für das ContextMenu gedacht, hab den da jetzt aus den Popover Props rausgenommen
