### ISSUE TITLE
Outlined variant for Accordion?

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/flow#553]
The [developer portal](https://github.com/mittwald/developer-portal) uses the `Accordion` component to present possible HTTP responses to an API operation ([example](https://developer.mittwald.de/docs/v2/reference/project/project-accept-project-invite/)).

In this instance, the Accordions contain quite a bit of content, and there are multiple accordions stacked on top of each other.

![Screenshot 2024-06-26 at 10 33 40](https://github.com/mittwald/flow/assets/2538958/6ada907d-4c2f-4c1b-9ad0-c1d090c3e4ae)

While this works in general, I find this a bit visually confusing because it's difficult to comprehend where the content of one Accordion ends and the next one begins.

My first idea for a solution would be an outlined variant of the Accordion; however, I'm also open to other solutions.

**Comment by mfal** [comment]
Thanks for you feedback! This seems to be a good idea and will be implemented soon.
