### ISSUE TITLE
Inconsistent Header with StatusBadge rendering in Modal

### ISSUE THREAD

**Issue by maaaathis** [mittwald/flow#556]
Previously, it was possible to set a Header with a StatusBadge in one line within a Modal, as demonstrated in the example provided here: [Mittwald Flow - Section Component](https://mittwald.github.io/flow/03-components/structure/section).

However, in recent versions, this functionality has broken. While the Header with StatusBadge still works correctly in a standard Section outside of a Modal, within a Modal, the Heading unexpectedly moves outside the Header into the Modal's "title" slot:
![image](https://github.com/mittwald/flow/assets/37186532/7854366e-fcab-499e-b081-0e1ee5854908)

**Comment by Lisa18289** [comment]
Wir haben hier grad nochmal was angepasst, du kannst den StatusBadge jetzt einfach direkt in die Heading stecken.
