### ISSUE TITLE
Modal Content is not scrollable

### ISSUE THREAD

**Issue by freisenhauer** [mittwald/flow#589]
If Modal Content gets too large, the content gets cut off and is not scrollable.

**Comment by mfal** [comment]
1. I can not reproduce this behavior. Reduce the height of your browser window and try it out by your own: https://mittwald.github.io/flow/03-components/overlays/modal. Maybe you can provide some example code.
2. A Modal with much content might be better displayed in the Off-Canvas variant. Also see: https://mittwald.github.io/flow/03-components/overlays/modal
