### ISSUE TITLE
Buttons dont get pressed when using Vimium

### ISSUE THREAD

**Issue by freisenhauer** [mittwald/flow#590]
If using vimium Buttons actions dont get called. The Button just stays in "pressed" representation (getting a little darker) and nothing happens.

Here you can see, which events vimium triggers to simulate a click: 
https://github.com/philc/vimium/blob/master/lib/dom_utils.js#L367

```javascript

simulateClick(element, modifiers) {
    if (modifiers == null) modifiers = {};
    const eventSequence = [
      "pointerover",
      "mouseover",
      "pointerdown",
      "mousedown",
      "pointerup",
      "mouseup",
      "click",
    ];
    for (const event of eventSequence) {
      this.simulateMouseEvent(event, element, modifiers);
    }
  },

```

**Comment by mfal** [comment]
How does the Button from React Aria works with Vimium?
https://react-spectrum.adobe.com/react-aria/Button.html

**Comment by freisenhauer** [comment]
Ah I see, you are using react-aria buttons. These don't work either.🫠 
I will report this bug to them.

**Comment by mfal** [comment]
@freisenhauer can this be closed, since it is reported upstream?
