### ISSUE TITLE
Skeleton component don't work as expected

### ISSUE THREAD

**Issue by TimAufdemKampe** [mittwald/flow#597]
![Bildschirmfoto 2024-07-17 um 13 05 46](https://github.com/user-attachments/assets/aa5bf993-f170-4197-841b-bf2ee00e054f)

The skeleton component only reacts correctly to the `className` property. The `style` prop will the passed into the outer container of the skeleton. Not on the skeleton itself.

![Bildschirmfoto 2024-07-17 um 13 08 14](https://github.com/user-attachments/assets/9228e75f-fee2-4dc9-9560-d022babff440)

The correct div for the skeleton is the div with the class "flow--skeleton".

**Comment by mfal** [comment]
The issue you reported is a regression introduced by fa4ea9c0d75e110df458130a158ef6667a768aef. So a revert should be ok.

But we still need a Skeleton component, that behaves like text with a given line-height and font-size. Compare the loading view of the List items, to see the difference:

- after your change: https://mittwald.github.io/flow-previews/storybook/fix/skeleton/?path=/story/structure-list--default
- and before: https://mittwald.github.io/flow-previews/storybook-main/?path=/story/structure-list--default

I would suggest the following:

- copy over the current `Skeleton` to `SkeletonText`, fix the `className` issue and remove the `height` prop
- revert the commit fa4ea9c0d75e110df458130a158ef6667a768aef
