### ISSUE TITLE
Add customization option for the default message if nothing is entered in the list component

### ISSUE THREAD

**Issue by JLampeMW** [mittwald/flow#652]
It would be nice if the default message of an empty list could be customized. It is very confusing when it says ‘No search results found’ but the extension context does not match at all.

![Bildschirmfoto 2024-08-23 um 15 16 14](https://github.com/user-attachments/assets/b47468d7-3769-4d81-af58-fe9133ccd0c2)

**Comment by Lisa18289** [comment]
Würde es in dem Fall nicht Sinn ergeben die Liste einfach auszublenden wenn sie leer ist?
