### ISSUE TITLE
Adjustment of the code font

### ISSUE THREAD

**Issue by kati-ux** [mittwald/flow#674]
A code font must be different from a regular font. A code font must look technical, have good code readability and be monospaced. **Fira Code** fulfills these requirements and should therefore be used as a new code font. Fira Code also has the advantage that it has practical code ligatures.
![Code](https://github.com/user-attachments/assets/e39e3ae7-0e57-4a57-8938-bc2f39c1e7b9)

**Comment by Jan-Eimertenbrink** [comment]
I have adapted it in our Figma library ✅ 

Fira Code; Regular; 14p; lh 150%
