### ISSUE TITLE
Side-by-side Info Boxes should have same height

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#677]
See Do/Don't component
![Bildschirmfoto 2024-09-03 um 09 38 48](https://github.com/user-attachments/assets/55b76623-4c54-4d34-a679-bd11b8300528)
![Bildschirmfoto 2024-09-03 um 09 38 39](https://github.com/user-attachments/assets/2b637a08-7855-4e28-857c-1a55e6139279)

**Comment by mariejuenke** [comment]
works with the same wrapper box as do/don't /close
