### ISSUE TITLE
Too large clickable area for the GitHub link

### ISSUE THREAD

**Issue by Jan-Eimertenbrink** [mittwald/flow#706]
I noticed that the clickable area of the GitHub link on each page is significantly too large. This is particularly noticeable when focusing with the keyboard or when hovering over the empty space with the mouse. Maybe it's a small fix for @mariejuenke ?

![Bildschirmfoto 2024-09-12 um 16 13 43](https://github.com/user-attachments/assets/1b0b7708-d407-4a6e-9fd9-55878b0952e0)

**Comment by mfal** [comment]
Also at "Feedback geben" link
