### ISSUE TITLE
Possible Improvement for ColumnLayout

### ISSUE THREAD

**Issue by Nickzlos** [mittwald/flow#710]
## Problem Description
Currently, the `ColumnLayout` component allows for flexible adjustments of the number of columns and their size ratios, even across different breakpoints. However, one limitation is that the vertical and horizontal spacing between the columns cannot be customized.

This becomes particularly problematic when nesting one **ColumnLayout** within another to create grouped elements. For example, when designing a form for an address, you might want a standard spacing of 32px between fields, but for "Street" and "Number" fields, you may prefer a smaller spacing of 16px to visually group them more closely.

## Proposed Solutions
**Option 1: Predefined Spacing Sizes (s, m, l):** Each `ColumnLayout` could be assigned a predefined spacing size (small, medium, large) through a property like `spacing`. By default, the spacing could be set to `m`, corresponding to a 16px gap between the columns and rows. For a nested `ColumnLayout`, you could assign a spacing value of `s`, which would reduce the spacing to 8px, helping visually group related elements together.

**Option 2: Separate Controls for Horizontal and Vertical Spacing:** Another approach could be to allow different spacing values for horizontal and vertical gaps. This could still use predefined properties (`s`, `m`, `l`), but with the flexibility to assign different values for vertical and horizontal spacing. For example, you could set `s` for the vertical gap and `m` for the horizontal gap, creating a spacing of 8px to the sides and 16px to top and bottom. This would provide more granular control over the layout.

## Benefits
Both approaches would enhance flexibility in designing responsive layouts and improve the visual grouping of nested `ColumnLayout` components. Option 1 provides a straightforward solution with predefined spacing options, ensuring consistency but offering slightly less flexibility. Option 2, while more flexible, introduces a higher risk of inconsistency or errors when configuring the layout.

We’d love to hear the community’s thoughts and feedback on these proposed improvements.

**Comment by Jan-Eimertenbrink** [comment]
We will create a mixture of Option 1 and Option 2. With the `gap` property, both the horizontal and vertical spacing can be set to a specific value, such as `m`. The `columngap` property allows adjustment of vertical spacing, while `rowgap` adjusts horizontal spacing.

The sizes will be `s = 8px`, `m = 16px` (standard), and `l = 32px`. 

If no size is specified, `gap ` will be set to default (16px).
