### ISSUE TITLE
Cursor should not be "text" when hovering over Select Option

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#711]
<img width="1130" alt="Bildschirmfoto 2024-09-13 um 10 18 07" src="https://github.com/user-attachments/assets/0482ae22-5247-4fa2-8abd-87a2f3427c9d">

**Comment by JLampeMW** [comment]
Die Seite https://mittwald.github.io/flow/03-components/form-controls/select scheint das irgendwie anders zu handeln. Im Storybook als auch bei der DomainTransfer Extension wo auch das Select mit Options verwendet wird kommt kein Cursor Text. Es wird auch nicht spezifisches in der Select Component gesetzt was den cursor betrifft.
