### ISSUE TITLE
Country selection component

### ISSUE THREAD

**Issue by Jan-Eimertenbrink** [mittwald/flow#716]
## Description  
The country selection is based on a select component, but it is linked to a library of countries. This component allows the user to quickly find the desired country, thanks to an integrated search and flag emojis preceding the country names.

## Design  
Here is an older design:

![Bildschirmfoto 2024-09-16 um 08 23 16](https://github.com/user-attachments/assets/81c6a952-2a2b-46c2-a238-bb721a471178)

A new design will need to be developed when implementation begins.

**Comment by thueske** [comment]
We should definitely talk again about how the flags are displayed. The use of emojis is not the best solution, depending on the end device.

**Comment by Jan-Eimertenbrink** [comment]
> We should definitely talk again about how the flags are displayed. The use of emojis is not the best solution, depending on the end device.

Thank you for the hint! I've noted it down, and we will keep an eye on it during implementation. After some research, I found out that Windows, in particular, seems to avoid country flag emojis, which could pose a problem in our case. However, there is the possibility to embed a font, as described in this [article](https://fullystacked.net/using-emoji-on-the-web/#:~:text=By%20default%2C%20most%20browsers%20utilise,be%20Microsoft%20Segoe%20Color%20Emoji.), to work around the issue.

I suggest **we begin without using emojis** for now and later decide if it's worth adding them. I do see the potential from a UX perspective that using country flags could improve the experience, making it easier for users to find their country. However, we should carefully weigh the effort against the benefit during implementation.

**Comment by maaaathis** [comment]
implemented in #1043
