### ISSUE TITLE
CodeBlock component

### ISSUE THREAD

**Issue by Jan-Eimertenbrink** [mittwald/flow#720]
## Overview
In addition to InlineCode and the CodeEditor, we also want to include a CodeBlock in our design system. The CodeBlock is characterized mainly by its syntax highlighting and serves to display code and allow it to be copied.

## Concept
We’ve designed a CodeBlock which integrates the existing React Syntax Highlighter. This component is designed to handle code display while utilizing syntax highlighting, and we’ve focused on ensuring accessibility and consistency across themes.

To maintain familiarity for users, we built the CodeBlock around the default theme of the syntax highlighter. A default, light and dark variant has been created, each ensuring a minimum contrast ratio of 4.5:1 between the text and background to meet accessibility standards.

## Implementation
The CodeBlock component was designed and prototyped in Figma.
We introduced a new approach to the token structure, ensuring InlineCode and CodeBlock components share as much of the same code token structure as possible.

–– 

Please reach out to the issue creator or UX for further details before proceeding.

**Comment by thueske** [comment]
Interested in 👍🏻
