### ISSUE TITLE
Accordion Enhancement

### ISSUE THREAD

**Issue by Jan-Eimertenbrink** [mittwald/flow#754]
## Description
We noticed that the accordion in its outline variant has very small paddings. To make the design appear more visually appealing and less cramped, we decided to increase the horizontal padding from 4px to 8px and the vertical padding from 2px to 4px.

### Before the changes

![Bildschirmfoto 2024-09-20 um 10 38 44](https://github.com/user-attachments/assets/85f6ce56-31c5-41fb-a524-c94edf8efe85)

### After the changes
![Bildschirmfoto 2024-09-20 um 10 38 51](https://github.com/user-attachments/assets/8f8cc413-006d-4f5c-b7a4-c39e6cc6c8c9)

## Tokens
The following tokens were adjusted:

```
  --accordion-padding-x: var(--size-s);
  --accordion-padding-y: var(--size-xs);
```

**Comment by elmartinezc** [comment]
It seems that the spacing has already been 8px horizontally and 4px vertically at least since May so I'll close this.
See here: https://github.com/mittwald/flow/blob/a879bdb296ef148c6e08420d6439a304ab529690/packages/design-tokens/src/components/accordion.yml#L7-L10
