### ISSUE TITLE
Label-Value 4px to 2px

### ISSUE THREAD

**Issue by Caro-Steinborn** [mittwald/flow#788]
We change the Label-Value height from 4px to 2px. We looked at all the possible uses of the label and realised that the distance of 4px is too large. I refer to the law of proximity: 'Elements that are close to each other are perceived as belonging together,' which supports the choice of 2px.

![Bildschirmfoto 2024-09-26 um 10 09 47](https://github.com/user-attachments/assets/26d54952-f1d6-4f25-9be8-225153d4f52e)

**Comment by Jan-Eimertenbrink** [comment]
As far as I know, we need to make adjustments in two places: first, in the form control from XS to XXS, and second, in the labeled value from XS to XXS.

### Affected Token

`form-control: label-to-control-spacing: value: "{size-rem.xs}"`

`labeled-value: label-to-value-spacing: value: "{size-rem.xs}"`

I have already adjusted it in Figma on our side.

**Comment by deder-mw** [comment]
Resolved by #817
