### ISSUE TITLE
Intro Section Without Image for Foundations

### ISSUE THREAD

**Issue by Nickzlos** [mittwald/flow#793]
### Description
Currently, each content begins with an introductory section that provides a brief overview of the topic. This works well on the component pages, where there is a clear visual separation between the introduction and the main content. However, on the foundations pages, this separation is missing because we only have one version of the intro section – the one with an image on the right side.

### Request
We need an additional variation of the intro section without an image, allowing for both layouts (with and without an image) to be utilized across different types of pages.

### Expected Enhancement
- A visually distinct intro section on foundation and component pages.
- Increased recognition and consistency within the content, enabling users to learn what to expect in the intro section across all pages.

**Comment by BenniEngel** [comment]
Allready implemented
