### ISSUE TITLE
Add "Develop" Tab to Component Pages

### ISSUE THREAD

**Issue by Nickzlos** [mittwald/flow#799]
### Description
We would like to enhance the component pages by adding a new tab called "Develop" alongside the existing "Overview" and "Guidelines" tabs. The "Develop" tab will host content specifically targeted at developers, offering detailed, component-specific information.

### Request

- Add a new "Develop" tab to the component pages to provide a dedicated space for developer-focused content.
- Automate the display of all props associated with each component within the "Develop" tab.
- The props should be automatically generated and integrated into the style guide to always reflect the current state of the components without requiring manual updates.

### Expected Outcome
A clear, dedicated space for developer-specific information, enhancing the usability of the style guide for technical users.
Automated presentation of component props in the "Develop" tab, providing quick and valuable insights for developers without manual documentation effort.

**Comment by mfal** [comment]
Related issue https://github.com/mittwald/flow/issues/799
