### ISSUE TITLE
Improvements to Controls

### ISSUE THREAD

**Issue by Jan-Eimertenbrink** [mittwald/flow#802]
## Description
We want to improve our controls. The changes affect RadioButton, CheckboxButton, and SegmentedControl.

To make the focus state and the selected state even more distinct from each other, we have decided to remove the blue border in the selected state. We believe the Radio/Checkbox icon and the checkmark in the SegmentedControl are sufficient to signal to the user that the element is selected. Additionally, for users who can perceive colors, the background remains light blue. This gives our design the positive effect of appearing lighter and more elegant.

Furthermore, the checkmark for confirming selection in the SegmentedControl will now be displayed in text color. We introduced this change after realizing that the FormControl token, which we use in all our FormControls, included a "Content Selected" token that was solely intended for this blue checkmark. We questioned whether this was really necessary and were able to simplify the token as a result.

## Design 

![Bildschirmfoto 2024-09-27 um 11 56 34](https://github.com/user-attachments/assets/84b206be-cb18-49c8-a3f7-d46e75d0137e)

## Tokens
For the token, we use the token from the FormControls.

### Changes
`border-color-selected value: "{neutral-outline-border-color.selected}"` -> deleted
`content-color-selected value: "{neutral-outline-content-color.selected}" ` -> deleted

## Addition of Disabled Selected States
We discovered that we had forgotten to include the Disabled/Selected states for RadioButton, CheckboxButton, and the SegmentedControl. The corresponding tokens should already be included under the disabled tokens in the FormControls.

**Comment by elmartinezc** [comment]
It looks like this has already been resolved, correct me if I'm wrong about this @Jan-Eimertenbrink
