### ISSUE TITLE
Add description for Button outline variant in styleguide

### ISSUE THREAD

**Issue by elmartinezc** [mittwald/flow#815]
The outline variant for the Button component is currently missing a short description text in the styleguide.
The description is still work in progress at the moment and will need to be added once it is ready.

**Comment by Nickzlos** [comment]
Short description for outline variant and minor content changes / improvements have been implemented in -

https://github.com/mittwald/flow/pull/944 (Index)
https://github.com/mittwald/flow/pull/941 (Overview)
https://github.com/mittwald/flow/pull/943 (Guidelines)
