### ISSUE TITLE
Add Code of Conduct to the Repository

### ISSUE THREAD

**Issue by Brijeshthummar02** [mittwald/flow#849]
Explanation: We want to improve the inclusiveness and community standards of our business by including a code of conduct. This manual will help create a comfortable and welcoming environment for both providers and users.

Suggested Resources:

• A brief introduction to the purpose of the Code of Conduct
• A Guide to Respectful Communication
• expectations of behavior in the community
• Misconduct reporting procedures

Steps in reproduction:

• Create a new file named CODE_OF_CONDUCT.md in the root directory of the repository.
• Include the items listed above, as well as any additional items you deem necessary.

Expected Results:

A comprehensive code of conduct that aligns with the values ​​of our profession and is easily referenced by the entire community.

Labels: good first issue, documentation

**Comment by maaaathis** [comment]
I think https://www.contributor-covenant.org/ is a good starting point here. Maybe even directly the latest version 2.1: https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by mfal** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!
