### ISSUE TITLE
Add CONTRIBUTING.md File

### ISSUE THREAD

**Issue by Brijeshthummar02** [mittwald/flow#850]
Description :
Create a CONTRIBUTING.md file to guide contributors on how to participate in the project.

Action Items
1. Outline the project's purpose, setup instructions, code style, and PR submission process.
2. Draft the CONTRIBUTING.md file.
3. Review and finalize the document with core contributors.
4. Publish in the repository and link it in the README.
5. Announce its availability to the community.

**Comment by mfal** [comment]
👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!
