### ISSUE TITLE
Share a list of feedback (Documentation, Question, Feature)

### ISSUE THREAD

**Issue by gskyarts** [mittwald/flow#863]
Hi Flow-Team,

I'm using this library for the first time in my project, and while I haven't used everything yet, I wanted to share some feedback on what I found missing parts in the documentation or what didn't work well for me. Instead of creating separate tickets for each point, I thought I'd put everything in one.

- [ ] **Documentation**
    - [ ] #870
    - [x] #874
    - [x] #871
    - [ ] #872
    - [ ] #875
    - [x] #876

- [ ] **Questions**
    - [x] #868
    - [ ] #878

- [ ] **Component**
    - [x] #869

- [ ] **Feature**
    - [x] #879
    - [ ] #889
    - [x] #880
    - [x] #881
    - [x] #882
    - [x] #883
    - [ ] #884
    - [ ] #888
    - [ ] #885
    - [ ] #886
    - [ ] #887

Thanks for considering my feedback! i appreciate all your hard work on this library.

**Comment by mfal** [comment]
Thanks for your comprehensive feedback. I'll try to get to each point asap.

**Comment by mfal** [comment]
Hey @gskyarts 

I've moved and answered all your points in separate issues. I've close already some of them. If you still have questions, feel free to re-open them.

Thanks again for the feedback 🙏
