### ISSUE TITLE
Color info under Foundations > Design > Colors

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#872]
It would be super helpful to add color info under Foundations > Design > Colors

**Comment by Lisa18289** [comment]
color documentation is coming soon: https://github.com/mittwald/flow/pull/825

**Comment by mfal** [comment]
We are planning to add more infos in the foundation section.

@gskyarts I'm curious how this would help you from a developer perspective? Colors are generally documented on the component itself, like on the [Button](https://mittwald.github.io/flow/03-components/actions/button).

**Comment by mfal** [comment]
[Color docs](https://mittwald.github.io/flow/02-foundations/01-design/02-colors) are live.
