### ISSUE TITLE
Can you add a keyboard shortcut (Ctrl + K or Cmd + K) to open the search? That's pretty common in many documentations.

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#879]

**Comment by gskyarts** [comment]
I think there was a misunderstanding regarding my suggestion.

Could you add a full-page search feature to your documentation, accessible via a shortcut like Cmd+K or Ctrl+K?

Many documentation sites, like Bootstrap and Vercel, have this feature, allowing users to quickly find information. Implementing something similar would be handsome. What do you think?

**Comment by mfal** [comment]
😅 Ahh! Good idea: https://github.com/mittwald/flow/issues/889#issuecomment-2429485603
