### ISSUE TITLE
Why can't we create a table without TableHeader?

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#885]
Table :: The Table component can be a bit annoying sometimes. Why can't we create a table without TableHeader? Not every table needs one.

**Comment by mfal** [comment]
@gskyarts I'm not 100% sure, but a table without a header might not be accessible. Maybe you can use the [`<List />`](https://mittwald.github.io/flow/03-components/structure/list) to display the informations?

**Comment by Jan-Eimertenbrink** [comment]
Table headers are essential for users to understand the content in the columns. For example, take a table where each column contains a date. Without a header that explains the context, this date could represent anything: creation date, last contact date, due date, birthday, etc. Only a table header provides the necessary clarity.

If data or elements are not meant to be displayed in columns, a list (as Marco already pointed out) can be used effectively. It is important that the information clearly indicates what it refers to, for example, a subtitle like "Created on [Date]".
