### ISSUE TITLE
InlineComponent nicht im Text inlined

### ISSUE THREAD

**Issue by patrickhilker** [mittwald/flow#900]
```
<LayoutCard>
  <Section>
    <Heading level={1}>Ein Fehler ist aufgetreten</Heading>
    <Text>
      Häufig ist das Problem eine ungültige <InlineCode>.user.ini</InlineCode>-Datei in deinem App-Verzeichnis. Bitte überprüfe die Syntax und lösche die Datei ggf. einfach.
    </Text>
  </Section>
</LayoutCard>
```

https://github.com/user-attachments/assets/81660eba-6a2b-4956-9e00-ef30cd432a44

**Comment by Lisa18289** [comment]
@patrickhilker hast du da noch eigenes css drin, bzw tritt das Problem noch auf? Ich hab den Code kopiert, aber bei mir sieht das richtig aus:
![Image](https://github.com/user-attachments/assets/a98975e7-9c03-4059-ac0f-2b57caa2410b)
