### ISSUE TITLE
Implement a Footer

### ISSUE THREAD

**Issue by Nickzlos** [mittwald/flow#904]
## Description
We have designed a footer for our styleguide which is waiting to be implemented.

The design  is divided into two sections:

- On the left: important links and navigation elements.
- On the right: a feedback section, which will be visually enhanced with an image.

For tablet portrait view and smaller, the image in the feedback section should be hidden. The breakpoints will follow common values used in the rest of the styleguide. According to discussions with @Lisa18289 , the best approach is to fine-tune this during implementation.

![Image](https://github.com/user-attachments/assets/d76d9a6f-fcb4-469a-9e8b-f21dddd4f9e5)

![Image](https://github.com/user-attachments/assets/0df6abef-debb-4a3e-82cb-766d8370df4b)

### Content and Semantic Markup
Currently, the following links are displayed:

[GitHub Repository](https://github.com/mittwald/flow)
[Developer Portal](https://developer.mittwald.de/)
[Mittwald Imprint](https://www.mittwald.de/impressum)
[Mittwald Privacy Policy](https://www.mittwald.de/datenschutz)

The feedback section should link directly to the issue board and pre-select a template, which is being worked on in parallel issue.

### Accessibility

An accessibility review regarding the marking of links in the footer has determined that:

- The footer itself must be marked as such.
- Groupings of links should be marked with an appropriate heading.
- Even in the footer, no heading level should be skipped
- This leads to a footer structured as follows:

```
<footer>
   <h2 class="visually-hidden">Footer</h2>
      <h3>Menu</h3>
         <ul>
            <li>Link</li>
            <li>Link</li>
            <li>Link</li>
          </ul>
</footer>
```

Please reach out to the issue creator for further details before proceeding. :)

**Comment by ChaudaryHammad** [comment]
Hi, @Nickzlos I want to work on this you can assign me.

**Comment by mfal** [comment]
@Nickzlos what I am always searching for is the backlink to the Github project start page (I know there are links to the components themselves).

Could we also add to the footer maybe?

**Comment by thueske** [comment]
The footer is not implemented as in the concept (logo positioning). The scrollable area is also too long.

**Comment by Nickzlos** [comment]
Further adjustments:
- Rename "Contributoren-Seiten" to "Ressourcen" for a better and more broad understanding
- Padding top / sides is to small, should be 64px
- Nest the footer in more than one column layout, so that it is grouped according to this picture. The link-sections + the feedback section are separated with 32px to each other and 32px to the logo. The content all together is spaced 64px from the illustration.
Text me if there are further questions. 
![Image](https://github.com/user-attachments/assets/099c9db2-94c5-4b80-ac68-2c14218f021a)
