### ISSUE TITLE
Styleguide Header Design Optimization

### ISSUE THREAD

**Issue by Nickzlos** [mittwald/flow#905]
### Description
There are a few minor discrepancies between the current styleguide header and the design that need to be corrected.
Below are the specific issues that should be addressed:

- #### Wave Integration or Color Update:
Please integrate the "Wave" element from the design, or at least change the color of the header background to `hosting-blue-200`.

- #### Margin adjustment
Ensure there is a `24px` margin between header and content area.

- #### Logo and Text Margin:
The margin between the Mittwald logo and the adjacent text should be `16px`.

- #### Logo and "flow"-text alignment:
Currently the "Flow"-Lettering doesn't align perfectly to the mittwald logo. It should align evenly at the bottom as shown in this picture: 

![Image](https://github.com/user-attachments/assets/f5ad875a-4f4b-49f6-ac7e-81594edb1e92)

- ### Remove h1-Tag
The "Flow" should not have a h1-Tag. It's part of the logo and not a part of the information architecture.

Refer to the creator of this issue for question and/or further instructions.
Thank you for your help!

**Comment by palidii** [comment]
@Nickzlos I would like to try it, can you assign it to me? is it about the logo of the website?

**Comment by Nickzlos** [comment]
Hey @palidii ,

Thanks for reaching out and your interest in helping. We appreciate the enthusiasm and the offer to contribute :)

Right now, we're still in the early stages of building the foundation. There's still a lot of internal communication happening behind the scenes, so we're not quite ready to bring in outside contributions just yet.

Once we reach an "official" V1, we’d love to have you onboard!
Looking forward to opening things up for contributions in the future. It's awesome to know there are people like you who are excited to jump in.

Thanks for your patience and understanding.
