### ISSUE TITLE
css import on version 0.1.0-alpha.304 is wrong

### ISSUE THREAD

**Issue by gskyarts** [mittwald/flow#925]
Hi,

in your documentation you write 

> Styles importieren
Um die Komponenten Styles zu verwenden, musst du das Stylesheet importieren. Füge diese Zeile zum Einstiegspunkt deines Projektes hinzu. import "@mittwald/flow-react-components/core/styles.css";

but the path didn't exist anymore I need this currently `import "@mittwald/flow-react-components/all.css";`

**Comment by mfal** [comment]
Thanks @gskyarts!
