### ISSUE TITLE
Missing property descriptions

### ISSUE THREAD

**Issue by gskyarts** [mittwald/flow#995]
Hi,

There are always missing descriptions of the various properties. For example, the List component, where I just wanted to find out exactly what the batchSize property is, but unfortunately there is nothing. This is also the case with some other properties and components. I am missing whether this property is optional or not and which values I can use or are possible. Can you update this?

**Comment by Jan-Eimertenbrink** [comment]
Hey Giovanni,
Expanding the property descriptions is something we already have planned. However, at the moment, we don’t have the time to implement it. If you have any questions about specific components and their properties, feel free to reach out again. We’d be happy to help you directly in a personal conversation.
